# frontend/Dockerfile

FROM node:20

# Carpeta de trabajo
WORKDIR /app

# Copiar solo package.json para cache
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código fuente
COPY . .

# Construir build de producción con Vite
RUN npm run build

# Exponer puerto del preview de Vite (4173)
EXPOSE 4173

# Usar Vite Preview, no serve
CMD ["npm", "run", "preview", "--", "--host"]
